sudo: required

language: go

go:
  - 1.12.x

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx


cache:
  directories:
    - vendor

addons:
  apt:
    packages:
      - iproute2

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install iproute2mac; fi

install: make install_ci

script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ip a; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ip link; fi
  - make test
